# I AM VERY BROKEN DUE TO CHANGES TO STRUCTURE

version: "3.8"
services:
  product_service:
    # restart: on-failure
    depends_on:
      - product_db
    build:
      context: ./services/product
      target: development
    volumes:
      - ./services/product:/product_service
      - /product_service/node_modules
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:pass@product_db:5432/db
      API_VERSION: 1

  user_service:
    depends_on:
      - user_db
    build:
      context: ./services/user
      target: development
    volumes:
      - ./services/user:/user_service
      - /user_service/node_modules
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: mongodb://root:mongodbpassword@user_db:27017/db?authSource=admin
      API_VERSION: 1

  # location_service:
  #   # restart: on-failure
  #   depends_on:
  #     - location_db
  #   build:
  #     context: ./services/location
  #   volumes:
  #     - .:/services/location
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     DATABASE_URL: postgres://user:pass@postgres:5434/db
  #     API_VERSION: 1

  product_db:
    image: postgres:12.7
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./postgres-data/product:/var/lib/postgresql/data

  user_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
    # volumes:
    #   - ./postgres-data/user:/var/lib/postgresql/data

  # location_db:
  #   image: postgres:12.7
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: db
