export enum UserChannels {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
}

export enum AuthChannels {
  ON_AUTH = "ON_AUTH",
  ON_VALIDATE = "ON_VALIDATE",
}

export enum ProductChannels {
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_DELETED = "PRODUCT_DELETED",
}

export enum BrandChannels {
  BRAND_CREATED = "BRAND_CREATED",
  BRAND_UPDATED = "BRAND_UPDATED",
  BRAND_DELETED = "BRAND_DELETED",
}

export enum ProductTypeChannels {
  PRODUCT_TYPE_CREATED = "PRODUCT_TYPE_CREATED",
  PRODUCT_TYPE_UPDATED = "PRODUCT_TYPE_UPDATED",
  PRODUCT_TYPE_DELETED = "PRODUCT_TYPE_DELETED",
}

export enum LocationChannels {
  LOCATION_PRODUCT_UPDATED = "LOCATION_PRODUCT_UPDATED",
}

export enum HouseChannels {
  HOUSE_DELETE = "HOUSE_DELETED",
  HOUSE_UPDATED = "HOUSE_UPDATED",
  HOUSE_ADDED = "HOUSE_ADDED",
}
