FROM node:latest

# Allow environment to be overridden for testing etc.
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

# Set build version variable
ENV BUILD_VERSION "Development build"

# Default to port 80 for node, and 9229 and 9230 for debugger
ARG PORT=3001
ENV PORT $PORT

WORKDIR /code

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

# Install packages
RUN npm ci

# We assume the source code has been volume mounted

# May be better to run the following with node command, due to exit signals. We try NPM as a start though
CMD /bin/bash -c "ls -laAF && npm run dev --workspace=apis/location-service"